# Shadowrocket: 2026-05-06 23:05:58
[General]
# 绕过系统直连的局域网网段
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local,captive.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
# DNS 设置（仅用于直连域名解析，代理域名的 DNS 请求会直接发往远端服务器）
#不要加入中国dns
dns-server = system, 8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1,94.140.14.14,94.140.15.15
ipv6 = false
dns-direct-fallback-proxy = false
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
use-local-host-item-for-proxy = false

[Rule]
AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP
AND,((PROTOCOL,UDP),(DEST-PORT,8080)),REJECT-NO-DROP


# 1. 局域网 IP 直连 (加上 no-resolve 防止针对局域网 IP 的域名进行本地反查)
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
IP-CIDR6,::1/128,DIRECT,no-resolve
IP-CIDR6,FC00::/7,DIRECT,no-resolve
IP-CIDR6,FE80::/10,DIRECT,no-resolve

# 5. 兜底规则：以上没有匹配到的，全部走代理（不触发本地 DNS 解析）
FINAL,PROXY
